env:
  matrix:
    secure: IH+BBq6gTZ91TCSkm3sUvoCLE56pC4hWHg0F1Ca9qrTmd/n6qMAJp51qwSfV6N+h8J30wAeJLeLBBKn+qe5Dk/u2Y72PegwZ7pTwIh39BPYA+tx6ExfF+RVP/buGHH8ctq3R4OABbn9mZuZ33OdY35xpukH0Rv7TvU+G+7cmmdj3kZmYPV1xp9gcb8YHh0aL02+aQbnuZS9IS1IAMwVzwDZETZpBXf0wc+sREGMYU1+omX0cGSsUmDDwCnW3xhdlJyxaEZXMAk49u+z4PF0AY7ZTG+AatQpyH2w99/u2cqWznX2AsteikTg6qYzJYPRCON4eJD4HgUsRmdNy9yRuSOBknJC3B9AtjjTs26Iwsi1McLOxLizZSKns9my3fdtu7qFXKTveQV60W8wpCe95RqDMuZqWDy6UkEo//vF8U8NvA9sbp835UDMiph6PSXAESP43OzmRUXZWlXmYoLzAI3duHsc+KaQ4zcGzoY7470k4klUcu8tlCrvsN+cnITNlY0lrmZx7yLlZwNgu7hOp35trN0KwaGwfsEYyr7H/nVZDhxTSGjfNTzyqEEhvBtG0/r8gV2M20MwC3uwlo2v1/IgrndcAEo64U5Wm85JeXhCMdXJjAQBqWNY1IGugxccqzNsdJnIGsK74swGLc2Gz6oajT/ZiGHDj7DhT6CbIH34=

sudo: required
services:
  - docker

dist: xenial

go:
  - "1.12.x"
language: go

script:
  - ./build.sh
